gorm:
  config: 'sslmode=disable TimeZone=Asia/Shanghai'
  log-zap: false
  log-mode: "info"
  auto-migrate: false
  max-idle-conns: 10
  max-open-conns: 100
  conn-max-lifetime: 1h
  conn-max-idle-time: 24h
  dsn:
    sources:
      - host: '127.0.0.1'
        port: '5432'
        db-name: 'gva'
        username: 'root'
        password: 'gdkid,,..'
      - host: ''
        port: ''
        db-name: ''
        username: ''
        password: ''
    replicas:
      - host: ''
        port: ''
        db-name: ''
        username: ''
        password: ''
      - host: ''
        port: ''
        db-name: ''
        username: ''
        password: ''
