# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[GF-VUE-ADMIN]'
  director: 'logs'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true