# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[github.com/flipped-aurora/gin-vue-admin/server]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true